version: '3.8'

services:
  nextjs:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:dappa@localhost:5432/wondr-db
      - JWT_SECRET=your_jwt_secret
      - NEXTAUTH_URL=http://localhost:3000
      - GITHUB_CLIENT_ID=GANTI_PAKE_GITHUB_CLIENT_MASING2
      - GITHUB_CLIENT_SECRET=GANTI_PAKE_GITHUB_SECRET_MASING2
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dappa
      POSTGRES_DB: wondr-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
